### ISSUE TITLE
cloudflare async mode

### ISSUE THREAD

**Issue by tveronezi** [microprofile/microprofile.io#48]
https://support.cloudflare.com/hc/en-us/articles/200169436

The application executes 'app/scripts/_.js' before loading 'app/scripts/_templates.js'. Please check cloudflare link above for more info.

**Comment by exabrial** [comment]
@tveronezi 

So is it working? or not working? What is the desired outcome?

**Comment by tveronezi** [comment]
All good bud. It's related to this commit: https://github.com/microprofile/gitpress/commit/1aba953509a1ee2ed3b7119ffae6fd310ad84e47
