### ISSUE TITLE
Create a single Blog Page

### ISSUE THREAD

**Issue by dblevins** [microprofile/microprofile.io#57]
We could get super fancy, but the minimum requirement is there needs to be a blog page for MicroProfile news at this week's JavaOne.

Let's say:

http://microprofile.io/blog/2016/09/microprofile-at-javaone

We need to give John Clingan the ability to fill in that page.  I've created a stub page here:

 - https://github.com/microprofile/blog/blob/master/2016/09/microprofile-at-javaone.adoc

We need it to go live when John says "go"

We don't need to create a full-on brand new blogging system with indexes, tags and all that. Don't even need a "blog" menu item at the top. We just need to get that page up and we can worry about how to generally do blog items better later.

It should generally use the site template.  Copy the template from this page and we can refine later:

 - http://microprofile.io/faq

**Comment by tveronezi** [comment]
this PR should address this: https://github.com/microprofile/gitpress/pull/11
