### ISSUE TITLE
Replace WebSphere logo

### ISSUE THREAD

**Issue by tbookless** [microprofile/microprofile.io#59]
Replace the WebSphere Liberty logo with an IBM logo, but the IBM logo should still link to the same place: https://developer.ibm.com/wasdev/websphere-liberty/

The microprofile.io site requires a white logo with a transparent background.

IBM is unable to supply a white logo with a transparent background before Java One on Monday, but they gave permission for us to generate one.  This is a link to the logos that IBM sent if we want to use one as a model.

https://drive.google.com/open?id=0B_vUx5R8AeBxZXlJZGdQaW1idUJJOV93YU1ZbG1RVmpTZGJr

Once we have a new logo,  it can be uploaded here:
https://github.com/microprofile/microprofile.io/tree/master/logos

We will then need to use the new logo to replace the WebSphere Liberty logo.

**Comment by tbookless** [comment]
On September 16, 2016 at 2:40:40 PM, Kevin Sutter (sutter@us.ibm.com) wrote:

Hi David,
I just reviewed the logos provided and didn't see one that was white with transparent background...  I'll have to request it, but that won't happen until next week.  In the mean time, do you what you need to do.  Thanks!

And, you are correct, we are attempting to replace the WebSphere Liberty logo with the IBM logo on the microprofile.io site.  The referenced link should stay the same:  https://developer.ibm.com/wasdev/websphere-liberty/

---------------------------------------------------
Kevin Sutter
STSM, Java EE and Java Persistence API (JPA) architect
e-mail:  sutter@us.ibm.com     Twitter:  @kwsutter
phone: tl-553-3620 (office), 507-253-3620 (office)    
LinkedIn: https://www.linkedin.com/in/kevinwsutter

**Comment by dblevins** [comment]
Looks like we had a white IBM logo checked in already and of the right size.  I've gone ahead and updated the site and did a redeploy with the help of Mr Fisher.
